version: '3.8'

services:
  #database section
  #orderdb: sql server
  orderdb:
    container_name: orderdb
    environment:
      SA_PASSWORD: "Passw0rd!"
      ACCEPT_EULA: "Y"
    restart: always
    volumes:
      - sqlserver_data:/var/opt/mssql
    ports:
      - "1432:1433"

  #productdb: mysql
  productdb:
    container_name: productdb
    environment:
      MYSQL_ROOT_PASSWORD: "Passw0rd!"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  #customerdb: postgres
  customerdb:
    container_name: customerdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=CustomerDb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  #basketdb: redis
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  #inventorydb: mongo
  inventorydb:
    container_name: inventorydb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  #infrastructure section
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@tedu-microservice.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/pgadmin
# web ui for docker compose 
  portainer:            
    container_name: portainer
    restart: always
    ports:
      - "8080:8080"
      - "9000:9000"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  # elasticsearch and kibana section
  elasticsearch:
    container_name: elasticsearch
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
  # microservices api sections
  product.api:
        container_name: product.api
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - AspNetCore_Urls=http://+:80
          - "ConnectionStrings:DefaultConnectionString=Server=productdb;Port=3306;Database=ProductDB;Uid=root;Pwd=Passw0rd!;"
        depends_on:
          - productdb
        ports:
            - "6002:80"
        restart: 
            always
  # customer api sections
  customer.api:
        container_name: customer.api
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - AspNetCore_Urls=http://+:80
          - "ConnectionStrings:DefaultConnectionString=Server=customerdb;Port=5432;Database=CustomerDb;User Id=admin;Password=admin1234"
        depends_on:
          - customerdb
        ports:
            - "6003:80"
        restart: 
            always
  
  # basket api sections
  basket.api:
        container_name: basket.api
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - AspNetCore_Urls=http://+:80
          - "CacheSettings:ConnectionString=basketdb:6379"
        depends_on:
          - basketdb
        ports:
            - "6004:80"
        restart: 
            always
  
  # ordering api sections
  ordering.api:
        container_name: ordering.api
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - AspNetCore_Urls=http://+:80
          - "ConnectionStrings:DefaultConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;Password=Passw0rd!;Encrypt=False;TrustServerCertificate=True"
        depends_on:
          - orderdb
        ports:
            - "6005:80"
        restart: 
            always

  inventory.api:
        container_name: inventory.api
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_HTTP_PORTS=80
          - ASPNETCORE_HTTPS_PORTS=443
          - "MongoDbSettings:ConnectionString=mongodb://inventorydb:27017"
          - "MongoDbSettings:DatabaseName=InventoryDb"
          - "MongoDbSettings:CollectionName=InventoryEntries"
        depends_on:
          - inventorydb
        ports:
            - "6006:80"
            - "5005:5005"
        restart: 
            always

  # API Gateway sections
  ocelot.apigw:
        container_name: ocelot.apigw
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - AspNetCore_Urls=http://+:80
          - "ElasticConfiguration:Uri=http://elasticsearch:9200"
        depends_on:
          - product.api
          - customer.api
          - basket.api
          - ordering.api
          - inventory.api
          - elasticsearch
        ports:
            - "5000:80"
        restart: 
            always
